
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5
  port: 5432

development:
  <<: *default
  database: dev

  username: dev

  password: dev

  host: localhost

test:
  <<: *default
  database: test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>