
common: &default_settings
  license_key: 58b3cfcccbfc2302fd205c643296cfbab700d21a


  app_name: My Application

  log_level: info

development:
  <<: *default_settings
  app_name: My Application (Development)


  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: My Application (Staging)

production:
  <<: *default_settings
  app_name: Task Manager (Production)
